### PR TITLE
Add 'subdomain' to dictionary

### PR DESCRIPTION
**Pull request by paked**

### CODE REVIEW

**Comment by paked** [comment]
Err, I ran the command provided in `lib/README` and it seems to have done a lot more than I was expecting it to do.

Anyone have any ideas what's happened?

cc: @zachlatta @MaxWofford

**Comment by zachlatta** [comment]
#119. Want to take a stab at fixing that too?

**Comment by paked** [comment]
@zachlatta I just reran the command again on Fedora, looks better... But still not the same.

In the interest of getting hackclub/meta#664 merged could we accept these faults? I'll try and take a crack at #119 later if you want.

**Comment by zachlatta** [comment]
Yup, this is great! Merging.

**Comment by zachlatta** [comment]
Just remember to re-run tests in hackclub/meta#664 once the deployment of Markcop from CircleCI tests is done.

**Pull request merged**
