### PR TITLE
Add shipit to dictionary

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
Shouldn't this be in backticks instead? Ex. `#shipit`.

On Mon, Feb 15, 2016 at 6:09 PM, JESSICA notifications@github.com wrote:

> Merged #75 https://github.com/hackclub/markcop/pull/75.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/markcop/pull/75#event-551432918.

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by jkwok91** [comment]
but it's already a link?

**Comment by maxwofford** [comment]
@zachlatta @jkwok91 Let's bring this ~~out back~~ here: https://github.com/hackclub/hackclub/pull/720

**Comment by zachlatta** [comment]
:+1:

Should we revert this for the time being?

On Mon, Feb 15, 2016 at 6:23 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta @jkwok91
> https://github.com/jkwok91 Let's bring this out back here:
> hackclub/hackclub#720 https://github.com/hackclub/hackclub/pull/720
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/markcop/pull/75#issuecomment-184477791.

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by jkwok91** [comment]
yes

2016-02-15 18:51 GMT-08:00 Zach Latta notifications@github.com:

**Pull request merged**
