### PR TITLE
Add reference link testing

### LINKED ISSUE #43: Test links which have been referenced
As we are now using `jsbinctl` we are using a _lot_ more reference links than before.

Markcop does not currently check these links to see if they are broken (see hackclub/hackclub#591)

### PR DESCRIPTION
**Pull request by paked**
Closes #43

### CODE REVIEW

**Comment by maxwofford** [comment]
@paked I've only done initial testing, but it seems like this ignores images in reference links: `[](broken-link)`

**Comment by paked** [comment]
@MaxWofford Are you intending to test further

**Comment by maxwofford** [comment]
@paked Yep!

**Comment by maxwofford** [comment]
@paked That was all that I found issues with when testing.

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by maxwofford** [comment]
@zachlatta I'm not aware of anything.

/cc @paked

**Comment by paked** [comment]
@MaxWofford @zachlatta Haven't had any time recently to finish this off.

**Comment by zachlatta** [comment]
@remixz: Any chance you'd want to try taking a stab at this?

To give some background, Markcop is a (pretty scary) bash script we wrote to validate our Markdown. It checks for relative link validity and for style violations.

**Comment by remixz** [comment]
:grimacing: Not especially... I'd say we move to a dedicated markdown parsing library that's well tested. Personal recommendation: https://github.com/wooorm/remark with https://github.com/wooorm/remark-lint

The rules `no-unused-definitions` and `no-undefined-references` should handle this case, as it'll ensure every reference is used, and that we don't call one that doesn't exist. It doesn't look like `remark-lint` has spell checking by default, but that probably wouldn't be too hard to add.

**Comment by paked** [comment]
@remixz :+1: to that so hard. I've always been a proponent for moving away from `regex` + `bash`. I'm happy to put aside some time to get this set up?

cc: @zachlatta @MaxWofford

**Comment by zachlatta** [comment]
Sure, let's open up a new issue to track using a real parser for Markcop. It'll probably take some time to get it to the point where it catches as many things as Markcop currently does, so I propose making the change for this issue in the existing script.

I can try to find time to take point on it.

**Comment by maxwofford** [comment]
@paked just a quick ping :pineapple:

**Comment by zachlatta** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
