### PR TITLE
Check for newlines before and after headers

### LINKED ISSUE #12: Headers should have leading and trailing newlines

### PR DESCRIPTION
**Pull request by maxwofford**
Closes #12

### CODE REVIEW

**Comment by maxwofford** [comment]
@zachlatta This is the new branch for this feature.

**Comment by zachlatta** [comment]
Should this error when there's a file with the following contents?

```
# Test

Bubbles are quite interesting.
# I just forgot a new line
```

**Comment by maxwofford** [comment]
@zachlatta Yep! Hold off on this PR. I might have grabbed the wrong commit.

**Comment by zachlatta** [comment]
:+1:

**Comment by maxwofford** [comment]
@zachlatta Just fixed it.

**Comment by zachlatta** [comment]
I am satisfied. Great work!

**Pull request merged**
